---
engines:
  sqlint:
    enabled: false
  tsqllint:
    enabled: false
  pmdsql:
    exclude_paths:
      - "src/main/resources/db/migration/**"
exclude_patterns:
  - "src/main/resources/db/migration/**"
  - "**/V1__init_prod_db.sql"
  - "**/V2__*.sql"
---
version: "2"
languages:
  sql:
    patterns:
      - "!src/main/resources/db/migration/**"