spring:
  datasource:
    url: jdbc:postgresql://postgres_prod:5432/${POSTGRES_PROD_DB}
    username: ${POSTGRES_PROD_USER}
    password: ${POSTGRES_PROD_PASSWORD}

  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

#  sql:
#    init:
#      mode: always # you won't do this in prod, I'm just doing this for demo purposes

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, info
  endpoint:
    health:
      show-details: always


