spring:
  datasource:
    # Use environment variable with fallback
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/devdb}
    username: admin
    password: admin
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, info
  endpoint:
    health:
      show-details: always
server:
  port: 8082