spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/${POSTGRES_TEST_DB}
    username: ${POSTGRES_TEST_USERNAME}
    password: ${POSTGRES_TEST_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop  # This will recreate the database schema for each test
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

server:
  port: 8087  # Different port for test environment

