spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/shop_db
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: prometheus, info, metrics, health  # Corrected syntax
server:
  port: 8081


