spring:
  datasource:
    # Use environment variable with fallback
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/devdb}
    username: ${POSTGRES_DEV_USER:admin}
    password: ${POSTGRES_DEV_PASSWORD:admin}
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    # Redis configuration
    redis:
      host: localhost
      port: 6380
      password: ${REDIS_PASSWORD}
      timeout: 2000

  # MongoDB configuration
  data:
    mongodb:
      uri: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@localhost:27017/${MONGO_DATABASE}?authSource=admin

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, info
  endpoint:
    health:
      show-details: always
server:
  port: 8082