spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/shop-test-db
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Uncomment the following lines if you want to use Flyway for database migrations
  # flyway:
  #   enabled: true
  #   locations: classpath:db/migration


server:
  port: 8088