spring:
  application:
    name: mini-shop
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: prometheus, info, metrics, health
  info:
    env:
      enabled: true
  # Jackson Configuration
jackson:
  time-zone: UTC
  date-format: yyyy-MM-dd HH:mm:ss

  # Security Configuration
  security:
    filter:
      order: 10

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION}
  refresh-token:
    expiration-ms: ${JWT_REFRESH_EXPIRATION}


server:
  port: 8082
  error:
    include-stacktrace: never
    include-message: always
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  # Increase the logging level for Spring Security config to remove the warning
logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration: ERROR