spring:
  datasource:
    url: jdbc:postgresql://postgres_docker:5432/${POSTGRES_DOCKER_DB}
    username: ${POSTGRES_DOCKER_USER}
    password: ${POSTGRES_DOCKER_PASSWORD}

  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  error:
    include-message: always
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus,info

  info:
    env:
      enabled: true
