CREATE TABLE public.customers
(
    customer_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    customer_name    VARCHAR(100) NOT NULL,
    customer_email   VARCHAR(50)  NOT NULL,
    customer_phone   VARCHAR(20)  NOT NULL,
    street           VARCHAR(50)  NOT NULL,
    street_number    VARCHAR(10)  NOT NULL,
    city             VARCHAR(50)  NOT NULL,
    country          VARCHAR(50)  NOT NULL,
    state            VARCHAR(15)  NOT NULL,
    zip_code         VARCHAR(10)  NOT NULL,
    apartment_number VARCHAR(10),
    floor_number     VARCHAR(10),
    CONSTRAINT pk_customers PRIMARY KEY (customer_id)
);

CREATE TABLE public.refresh_tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT,
    token       VARCHAR(255) NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

CREATE TABLE public.roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(20),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE public.user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE public.users
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    username               VARCHAR(50)  NOT NULL,
    password               VARCHAR(255) NOT NULL,
    enabled                BOOLEAN      NOT NULL,
    account_non_locked     BOOLEAN      NOT NULL,
    account_non_expired    BOOLEAN      NOT NULL,
    credentials_non_expired BOOLEAN      NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE public.customers
    ADD CONSTRAINT uc_customers_customer_email UNIQUE (customer_email);

ALTER TABLE public.refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_token UNIQUE (token);

ALTER TABLE public.refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_user UNIQUE (user_id);

ALTER TABLE public.users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

CREATE INDEX idx_customer_email ON public.customers (customer_email);
CREATE INDEX idx_customer_name ON public.customers (customer_name);
CREATE INDEX idx_customer_phone ON public.customers (customer_phone);

ALTER TABLE public.refresh_tokens
    ADD CONSTRAINT FK_REFRESH_TOKENS_ON_USER
        FOREIGN KEY (user_id) REFERENCES public.users (id);

ALTER TABLE public.user_roles
    ADD CONSTRAINT fk_userol_on_role
        FOREIGN KEY (role_id) REFERENCES public.roles (id);

ALTER TABLE public.user_roles
    ADD CONSTRAINT fk_userol_on_user
        FOREIGN KEY (user_id) REFERENCES public.users (id);